services:
  angular_app:
    container_name: angular_app
    image: pee-angular_app:1.0.0
    build: ./LecherosAppFrontend
    ports:
      - 4200:4200
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://java_db:3306/lecherosappdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: root
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:8.0.41
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: lecherosappdb